### ISSUE TITLE
fight odds 

### ISSUE THREAD

**Issue by ioannis12** [NateLatshaw/UFC-Analytics#1]
first of all congratulations for your work! 

I was wondering if it's possible to share the fight odds or make it replicable? I'm running a similar project and have a hard time getting data from bestfightodds

**Comment by NateLatshaw** [comment]
Sorry, I haven't gotten around to documenting my code well for others to reproduce.  To scrape the lines from historical events, all you need is the function in _Scraping Scirpts/scrape_UFC_odds_functions.R_. Then, after running the function, to scrape the lines from UFC 250, for example, just run the following code in R:

`library(rvest)`
`library(data.table)`
`library(lubridate)`
`library(zoo)`
`url = 'https://www.bestfightodds.com/events/ufc-250-nunes-vs-spencer-1909'`
`year = 2020`
`odds <- Scrape_BestFightOdds(url = url, year = year, eventID = 'Find')`

If you're looking to scrape lines for an upcoming event, you can use the same function, but the function only works when at least 1 prop bet has been added for each fight. Sometimes fights get added later such that the most recently added fight does not have prop bets but all other fights do. In this case the function should run, but the new fight without any props will not show up as its own fight. So be careful when scraping upcoming fights. Sometimes you have to wait a couple days for the site to add the prop bet lines. For upcoming events, just go to [https://www.bestfightodds.com/](url) and click on the title of table of the event you'd like to scrape, and that will take you the the URL you need to use in the function.

Is this what you're looking for?

**Comment by ioannis12** [comment]
thank you for the prompt reply, 
I just run the script and it works perfectly for the upcoming events

It's not exactly what I was looking for though. I have made predictions on ufc fights, and am looking for the matching historical odds to backtest the profitability of the predictions. For that I would need a big volume of historical odds

**Comment by NateLatshaw** [comment]
It should also work for historical fights. You just need to feed the function the URL and year of the event for each event you'd like. If you go here [https://www.bestfightodds.com/archive](url) you can search for past events.

One option is to manually collect the URLs and years for all the events you need in a csv or something, and then you can just loop through each event. This is what I've done for the past several UFC events. I use this for upcoming events at the moment, so I haven't gone back and scraped too many historical events. So I don't have a large backlog of data to share.

**Comment by ioannis12** [comment]
ok, I see, thanks for the replies :)
